#### general settings
name: 003_EDVRwTSA_scratch_lr4e-4_600k_HDR_L
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [0,1,2,3,4,5,6,7]

#### datasets
datasets:
  train:
    name: HDR
    mode: HDR
    interval_list: [1]
    random_reverse: false
    border_mode: false
    # dataroot_GT: ../datasets/HDR/train/lmdb/train_4k.lmdb
    # dataroot_LQ: ../datasets/HDR/train/lmdb/train_540.lmdb
    dataroot_GT: ../datasets/HDR/train/new_method/pngs/SDR_4K
    dataroot_LQ: ../datasets/HDR/train/new_method/pngs/SDR_540p
    cache_keys: ../datasets/HDR/train/lmdb/train_4k.lmdb/meta_info.pkl

    N_frames: 5
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 64
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: EDVR
  nf: 128
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 40 
  predeblur: False
  HR_in: False
  w_TSA: True

#### path
path:
  # pretrain_model_G: ../experiments/004_EDVRwoTSA_scratch_lr4e-4_600k_HDR_LrCAR4S/models/30000_G.pth
  # strict_load: false
  pretrain_model_G: ../experiments/002_EDVRwoTSA_scratch_lr4e-4_600k_HDR_L/models/140000_G.pth
  strict_load: false
  resume_state: ~
#../experiments/003_EDVRwoTSA_scratch_lr4e-4_600k_HDR_LrCAR4S/models/412000_G.pth:
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 2e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
